language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - "pip install flake8 pylint pytest requests"

script:
  - "make flake8"
  - "make pylint"
  - "make pytest"
