language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

install:
  - "pip install flake8 pylint pytest requests"

script:
  - "make flake8"
  - "make pylint"
  - "make pytest"
